// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";

// Import user types
import { StatmodOp, EleStat } from "./../Types.sol";

bytes32 constant _tableId = bytes32(abi.encodePacked(bytes16(""), bytes16("StatmodBaseOpts")));
bytes32 constant StatmodBaseOptsTableId = _tableId;

struct StatmodBaseOptsData {
  StatmodOp statmodOp;
  EleStat eleStat;
}

library StatmodBaseOpts {
  /** Get the table's schema */
  function getSchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](2);
    _schema[0] = SchemaType.UINT8;
    _schema[1] = SchemaType.UINT8;

    return SchemaLib.encode(_schema);
  }

  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _schema = new SchemaType[](1);
    _schema[0] = SchemaType.UINT256;

    return SchemaLib.encode(_schema);
  }

  /** Get the table's metadata */
  function getMetadata() internal pure returns (string memory, string[] memory) {
    string[] memory _fieldNames = new string[](2);
    _fieldNames[0] = "statmodOp";
    _fieldNames[1] = "eleStat";
    return ("StatmodBaseOpts", _fieldNames);
  }

  /** Register the table's schema */
  function registerSchema() internal {
    StoreSwitch.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Register the table's schema (using the specified store) */
  function registerSchema(IStore _store) internal {
    _store.registerSchema(_tableId, getSchema(), getKeySchema());
  }

  /** Set the table's metadata */
  function setMetadata() internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    StoreSwitch.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Set the table's metadata (using the specified store) */
  function setMetadata(IStore _store) internal {
    (string memory _tableName, string[] memory _fieldNames) = getMetadata();
    _store.setMetadata(_tableId, _tableName, _fieldNames);
  }

  /** Get statmodOp */
  function getStatmodOp(uint256 entity) internal view returns (StatmodOp statmodOp) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 0);
    return StatmodOp(uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get statmodOp (using the specified store) */
  function getStatmodOp(IStore _store, uint256 entity) internal view returns (StatmodOp statmodOp) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 0);
    return StatmodOp(uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set statmodOp */
  function setStatmodOp(uint256 entity, StatmodOp statmodOp) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    StoreSwitch.setField(_tableId, _primaryKeys, 0, abi.encodePacked(uint8(statmodOp)));
  }

  /** Set statmodOp (using the specified store) */
  function setStatmodOp(IStore _store, uint256 entity, StatmodOp statmodOp) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    _store.setField(_tableId, _primaryKeys, 0, abi.encodePacked(uint8(statmodOp)));
  }

  /** Get eleStat */
  function getEleStat(uint256 entity) internal view returns (EleStat eleStat) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    bytes memory _blob = StoreSwitch.getField(_tableId, _primaryKeys, 1);
    return EleStat(uint8(Bytes.slice1(_blob, 0)));
  }

  /** Get eleStat (using the specified store) */
  function getEleStat(IStore _store, uint256 entity) internal view returns (EleStat eleStat) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    bytes memory _blob = _store.getField(_tableId, _primaryKeys, 1);
    return EleStat(uint8(Bytes.slice1(_blob, 0)));
  }

  /** Set eleStat */
  function setEleStat(uint256 entity, EleStat eleStat) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    StoreSwitch.setField(_tableId, _primaryKeys, 1, abi.encodePacked(uint8(eleStat)));
  }

  /** Set eleStat (using the specified store) */
  function setEleStat(IStore _store, uint256 entity, EleStat eleStat) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    _store.setField(_tableId, _primaryKeys, 1, abi.encodePacked(uint8(eleStat)));
  }

  /** Get the full data */
  function get(uint256 entity) internal view returns (StatmodBaseOptsData memory _table) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    bytes memory _blob = StoreSwitch.getRecord(_tableId, _primaryKeys, getSchema());
    return decode(_blob);
  }

  /** Get the full data (using the specified store) */
  function get(IStore _store, uint256 entity) internal view returns (StatmodBaseOptsData memory _table) {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    bytes memory _blob = _store.getRecord(_tableId, _primaryKeys, getSchema());
    return decode(_blob);
  }

  /** Set the full data using individual values */
  function set(uint256 entity, StatmodOp statmodOp, EleStat eleStat) internal {
    bytes memory _data = encode(statmodOp, eleStat);

    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    StoreSwitch.setRecord(_tableId, _primaryKeys, _data);
  }

  /** Set the full data using individual values (using the specified store) */
  function set(IStore _store, uint256 entity, StatmodOp statmodOp, EleStat eleStat) internal {
    bytes memory _data = encode(statmodOp, eleStat);

    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    _store.setRecord(_tableId, _primaryKeys, _data);
  }

  /** Set the full data using the data struct */
  function set(uint256 entity, StatmodBaseOptsData memory _table) internal {
    set(entity, _table.statmodOp, _table.eleStat);
  }

  /** Set the full data using the data struct (using the specified store) */
  function set(IStore _store, uint256 entity, StatmodBaseOptsData memory _table) internal {
    set(_store, entity, _table.statmodOp, _table.eleStat);
  }

  /** Decode the tightly packed blob using this table's schema */
  function decode(bytes memory _blob) internal pure returns (StatmodBaseOptsData memory _table) {
    _table.statmodOp = StatmodOp(uint8(Bytes.slice1(_blob, 0)));

    _table.eleStat = EleStat(uint8(Bytes.slice1(_blob, 1)));
  }

  /** Tightly pack full data using this table's schema */
  function encode(StatmodOp statmodOp, EleStat eleStat) internal view returns (bytes memory) {
    return abi.encodePacked(statmodOp, eleStat);
  }

  /* Delete all data for given keys */
  function deleteRecord(uint256 entity) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    StoreSwitch.deleteRecord(_tableId, _primaryKeys);
  }

  /* Delete all data for given keys (using the specified store) */
  function deleteRecord(IStore _store, uint256 entity) internal {
    bytes32[] memory _primaryKeys = new bytes32[](1);
    _primaryKeys[0] = bytes32(uint256((entity)));

    _store.deleteRecord(_tableId, _primaryKeys);
  }
}
