// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { UniqueIdx_SOFClassName_Name } from "./idxs/UniqueIdx_SOFClassName_Name.sol";

function batchRegisterIdxs() {
  UniqueIdx_SOFClassName_Name.register();
}
