// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ERC721Config } from "./tables/ERC721Config.sol";
import { Name } from "./tables/Name.sol";
import { Experience } from "./tables/Experience.sol";
import { ActiveGuise } from "./tables/ActiveGuise.sol";
import { GuisePrototype } from "./tables/GuisePrototype.sol";
import { GuiseName } from "./tables/GuiseName.sol";
import { GuiseSkills } from "./tables/GuiseSkills.sol";
import { LearnedSkills } from "./tables/LearnedSkills.sol";
import { LifeCurrent } from "./tables/LifeCurrent.sol";
import { ManaCurrent } from "./tables/ManaCurrent.sol";
import { LootAffixes } from "./tables/LootAffixes.sol";
import { LootTargetId } from "./tables/LootTargetId.sol";
import { LootIlvl } from "./tables/LootIlvl.sol";
import { SkillTemplate, SkillTemplateData } from "./tables/SkillTemplate.sol";
import { SkillSpellDamage } from "./tables/SkillSpellDamage.sol";
import { SkillTemplateCooldown, SkillTemplateCooldownData } from "./tables/SkillTemplateCooldown.sol";
import { SkillTemplateDuration, SkillTemplateDurationData } from "./tables/SkillTemplateDuration.sol";
import { SkillName } from "./tables/SkillName.sol";
import { SkillDescription } from "./tables/SkillDescription.sol";
import { SkillCooldown, SkillCooldownData } from "./tables/SkillCooldown.sol";
import { ActiveCycle } from "./tables/ActiveCycle.sol";
import { BossesDefeated } from "./tables/BossesDefeated.sol";
import { CycleCombatRReq, CycleCombatRReqData } from "./tables/CycleCombatRReq.sol";
import { CycleTurns } from "./tables/CycleTurns.sol";
import { CycleTurnsLastClaimed } from "./tables/CycleTurnsLastClaimed.sol";
import { Wanderer } from "./tables/Wanderer.sol";
import { ActiveCombat, ActiveCombatData } from "./tables/ActiveCombat.sol";
import { CombatLogOffchain, CombatLogOffchainData } from "./tables/CombatLogOffchain.sol";
import { CombatLogRoundOffchain, CombatLogRoundOffchainData } from "./tables/CombatLogRoundOffchain.sol";
import { CombatLogActionOffchain, CombatLogActionOffchainData } from "./tables/CombatLogActionOffchain.sol";
import { FromMap } from "./tables/FromMap.sol";
import { RNGPrecommit } from "./tables/RNGPrecommit.sol";
import { RNGRequestOwner } from "./tables/RNGRequestOwner.sol";
import { SlotAllowedType } from "./tables/SlotAllowedType.sol";
import { SlotEquipment } from "./tables/SlotEquipment.sol";
import { EquipmentTypeComponent } from "./tables/EquipmentTypeComponent.sol";
import { OwnedBy } from "./tables/OwnedBy.sol";
import { MapTypeComponent } from "./tables/MapTypeComponent.sol";
