// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library ActiveWheel {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "wheel", name: "ActiveWheel", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462776865656c000000000000000000416374697665576865656c0000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0020010020000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32)
  Schema constant _valueSchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "cycleEntity";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "wheelEntity";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get wheelEntity.
   */
  function getWheelEntity(bytes32 cycleEntity) internal view returns (bytes32 wheelEntity) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get wheelEntity.
   */
  function _getWheelEntity(bytes32 cycleEntity) internal view returns (bytes32 wheelEntity) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get wheelEntity.
   */
  function get(bytes32 cycleEntity) internal view returns (bytes32 wheelEntity) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Get wheelEntity.
   */
  function _get(bytes32 cycleEntity) internal view returns (bytes32 wheelEntity) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (bytes32(_blob));
  }

  /**
   * @notice Set wheelEntity.
   */
  function setWheelEntity(bytes32 cycleEntity, bytes32 wheelEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((wheelEntity)), _fieldLayout);
  }

  /**
   * @notice Set wheelEntity.
   */
  function _setWheelEntity(bytes32 cycleEntity, bytes32 wheelEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((wheelEntity)), _fieldLayout);
  }

  /**
   * @notice Set wheelEntity.
   */
  function set(bytes32 cycleEntity, bytes32 wheelEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((wheelEntity)), _fieldLayout);
  }

  /**
   * @notice Set wheelEntity.
   */
  function _set(bytes32 cycleEntity, bytes32 wheelEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((wheelEntity)), _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 cycleEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 cycleEntity) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(bytes32 wheelEntity) internal pure returns (bytes memory) {
    return abi.encodePacked(wheelEntity);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(bytes32 wheelEntity) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(wheelEntity);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 cycleEntity) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = cycleEntity;

    return _keyTuple;
  }
}
