// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ActiveCombat, ActiveCombatData } from "./tables/ActiveCombat.sol";
import { CombatLogOffchain, CombatLogOffchainData } from "./tables/CombatLogOffchain.sol";
import { CombatLogRoundOffchain, CombatLogRoundOffchainData } from "./tables/CombatLogRoundOffchain.sol";
import { CombatLogActionOffchain, CombatLogActionOffchainData } from "./tables/CombatLogActionOffchain.sol";
