// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CombatStatus, CombatStatusData } from "./tables/CombatStatus.sol";
import { CombatActors } from "./tables/CombatActors.sol";
import { CombatLogRoundOffchain, CombatLogRoundOffchainData } from "./tables/CombatLogRoundOffchain.sol";
import { CombatLogActionOffchain, CombatLogActionOffchainData } from "./tables/CombatLogActionOffchain.sol";
