// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EquipmentSlotSystem } from "../../EquipmentSlotSystem.sol";
import { EquipmentType } from "../../EquipmentType.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type EquipmentSlotSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "equipment", name: "EquipmentSlotSys" }))
EquipmentSlotSystemType constant equipmentSlotSystem = EquipmentSlotSystemType.wrap(
  0x737965717569706d656e74000000000045717569706d656e74536c6f74537973
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title EquipmentSlotSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library EquipmentSlotSystemLib {
  error EquipmentSlotSystemLib_CallingFromRootSystem();
  error EquipmentSlotSystem_InvalidEquipmentType(EquipmentType equipmentType);

  function createEquipmentSlot(
    EquipmentSlotSystemType self,
    bytes32 ownerEntity,
    string memory name,
    EquipmentType equipmentType,
    ResourceId[] memory slotEntityScopedSystemIds
  ) internal returns (bytes32 slotEntity) {
    return
      CallWrapper(self.toResourceId(), address(0)).createEquipmentSlot(
        ownerEntity,
        name,
        equipmentType,
        slotEntityScopedSystemIds
      );
  }

  function createEquipmentSlot(
    EquipmentSlotSystemType self,
    bytes32 ownerEntity,
    string memory name,
    EquipmentType[] memory equipmentTypes,
    ResourceId[] memory slotEntityScopedSystemIds
  ) internal returns (bytes32 slotEntity) {
    return
      CallWrapper(self.toResourceId(), address(0)).createEquipmentSlot(
        ownerEntity,
        name,
        equipmentTypes,
        slotEntityScopedSystemIds
      );
  }

  function createEquipmentSlot(
    CallWrapper memory self,
    bytes32 ownerEntity,
    string memory name,
    EquipmentType equipmentType,
    ResourceId[] memory slotEntityScopedSystemIds
  ) internal returns (bytes32 slotEntity) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EquipmentSlotSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createEquipmentSlot_bytes32_string_EquipmentType_ResourceIdArray.createEquipmentSlot,
      (ownerEntity, name, equipmentType, slotEntityScopedSystemIds)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    return abi.decode(result, (bytes32));
  }

  function createEquipmentSlot(
    CallWrapper memory self,
    bytes32 ownerEntity,
    string memory name,
    EquipmentType[] memory equipmentTypes,
    ResourceId[] memory slotEntityScopedSystemIds
  ) internal returns (bytes32 slotEntity) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EquipmentSlotSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _createEquipmentSlot_bytes32_string_EquipmentTypeArray_ResourceIdArray.createEquipmentSlot,
      (ownerEntity, name, equipmentTypes, slotEntityScopedSystemIds)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    return abi.decode(result, (bytes32));
  }

  function createEquipmentSlot(
    RootCallWrapper memory self,
    bytes32 ownerEntity,
    string memory name,
    EquipmentType equipmentType,
    ResourceId[] memory slotEntityScopedSystemIds
  ) internal returns (bytes32 slotEntity) {
    bytes memory systemCall = abi.encodeCall(
      _createEquipmentSlot_bytes32_string_EquipmentType_ResourceIdArray.createEquipmentSlot,
      (ownerEntity, name, equipmentType, slotEntityScopedSystemIds)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    return abi.decode(result, (bytes32));
  }

  function createEquipmentSlot(
    RootCallWrapper memory self,
    bytes32 ownerEntity,
    string memory name,
    EquipmentType[] memory equipmentTypes,
    ResourceId[] memory slotEntityScopedSystemIds
  ) internal returns (bytes32 slotEntity) {
    bytes memory systemCall = abi.encodeCall(
      _createEquipmentSlot_bytes32_string_EquipmentTypeArray_ResourceIdArray.createEquipmentSlot,
      (ownerEntity, name, equipmentTypes, slotEntityScopedSystemIds)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    return abi.decode(result, (bytes32));
  }

  function callFrom(EquipmentSlotSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(EquipmentSlotSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(EquipmentSlotSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(EquipmentSlotSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(EquipmentSlotSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (EquipmentSlotSystemType) {
    return EquipmentSlotSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(EquipmentSlotSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _createEquipmentSlot_bytes32_string_EquipmentType_ResourceIdArray {
  function createEquipmentSlot(
    bytes32 ownerEntity,
    string memory name,
    EquipmentType equipmentType,
    ResourceId[] memory slotEntityScopedSystemIds
  ) external;
}

interface _createEquipmentSlot_bytes32_string_EquipmentTypeArray_ResourceIdArray {
  function createEquipmentSlot(
    bytes32 ownerEntity,
    string memory name,
    EquipmentType[] memory equipmentTypes,
    ResourceId[] memory slotEntityScopedSystemIds
  ) external;
}

using EquipmentSlotSystemLib for EquipmentSlotSystemType global;
using EquipmentSlotSystemLib for CallWrapper global;
using EquipmentSlotSystemLib for RootCallWrapper global;
