// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EquipmentSystem } from "../../EquipmentSystem.sol";
import { EquipmentType } from "../../EquipmentType.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type EquipmentSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "equipment", name: "EquipmentSystem" }))
EquipmentSystemType constant equipmentSystem = EquipmentSystemType.wrap(
  0x737965717569706d656e74000000000045717569706d656e7453797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title EquipmentSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library EquipmentSystemLib {
  error EquipmentSystemLib_CallingFromRootSystem();
  error EquipmentSystem_InvalidEquipmentType(bytes32 equipmentEntity);
  error EquipmentSystem_SlotNotAllowedForType(bytes32 slotEntity, EquipmentType equipmentType, bytes32 equipmentEntity);
  error EquipmentSystem_EquipmentEntityAlreadyEquipped(bytes32 equipmentEntity);

  function unequip(EquipmentSystemType self, bytes32 targetEntity, bytes32 slotEntity) internal {
    return CallWrapper(self.toResourceId(), address(0)).unequip(targetEntity, slotEntity);
  }

  function equip(EquipmentSystemType self, bytes32 targetEntity, bytes32 slotEntity, bytes32 equipmentEntity) internal {
    return CallWrapper(self.toResourceId(), address(0)).equip(targetEntity, slotEntity, equipmentEntity);
  }

  function spawnEquipmentSlots(EquipmentSystemType self, bytes32 ownerEntity) internal {
    return CallWrapper(self.toResourceId(), address(0)).spawnEquipmentSlots(ownerEntity);
  }

  function unequip(CallWrapper memory self, bytes32 targetEntity, bytes32 slotEntity) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EquipmentSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_unequip_bytes32_bytes32.unequip, (targetEntity, slotEntity));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function equip(CallWrapper memory self, bytes32 targetEntity, bytes32 slotEntity, bytes32 equipmentEntity) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EquipmentSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _equip_bytes32_bytes32_bytes32.equip,
      (targetEntity, slotEntity, equipmentEntity)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function spawnEquipmentSlots(CallWrapper memory self, bytes32 ownerEntity) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EquipmentSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_spawnEquipmentSlots_bytes32.spawnEquipmentSlots, (ownerEntity));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function unequip(RootCallWrapper memory self, bytes32 targetEntity, bytes32 slotEntity) internal {
    bytes memory systemCall = abi.encodeCall(_unequip_bytes32_bytes32.unequip, (targetEntity, slotEntity));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function equip(
    RootCallWrapper memory self,
    bytes32 targetEntity,
    bytes32 slotEntity,
    bytes32 equipmentEntity
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _equip_bytes32_bytes32_bytes32.equip,
      (targetEntity, slotEntity, equipmentEntity)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function spawnEquipmentSlots(RootCallWrapper memory self, bytes32 ownerEntity) internal {
    bytes memory systemCall = abi.encodeCall(_spawnEquipmentSlots_bytes32.spawnEquipmentSlots, (ownerEntity));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(EquipmentSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(EquipmentSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(EquipmentSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(EquipmentSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(EquipmentSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (EquipmentSystemType) {
    return EquipmentSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(EquipmentSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _unequip_bytes32_bytes32 {
  function unequip(bytes32 targetEntity, bytes32 slotEntity) external;
}

interface _equip_bytes32_bytes32_bytes32 {
  function equip(bytes32 targetEntity, bytes32 slotEntity, bytes32 equipmentEntity) external;
}

interface _spawnEquipmentSlots_bytes32 {
  function spawnEquipmentSlots(bytes32 ownerEntity) external;
}

using EquipmentSystemLib for EquipmentSystemType global;
using EquipmentSystemLib for CallWrapper global;
using EquipmentSystemLib for RootCallWrapper global;
