// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EffectDuration, EffectDurationData } from "./tables/EffectDuration.sol";
import { EffectTemplate, EffectTemplateData } from "./tables/EffectTemplate.sol";
import { EffectApplied, EffectAppliedData } from "./tables/EffectApplied.sol";
