// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ClaimCycleTurnsSystem } from "../../cycle/ClaimCycleTurnsSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ClaimCycleTurnsSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "ClaimCycleTurnsS" }))
ClaimCycleTurnsSystemType constant claimCycleTurnsSystem = ClaimCycleTurnsSystemType.wrap(
  0x73790000000000000000000000000000436c61696d4379636c655475726e7353
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ClaimCycleTurnsSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ClaimCycleTurnsSystemLib {
  error ClaimCycleTurnsSystemLib_CallingFromRootSystem();

  function claimCycleTurns(ClaimCycleTurnsSystemType self, bytes32 wandererEntity) internal {
    return CallWrapper(self.toResourceId(), address(0)).claimCycleTurns(wandererEntity);
  }

  function claimCycleTurns(CallWrapper memory self, bytes32 wandererEntity) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ClaimCycleTurnsSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_claimCycleTurns_bytes32.claimCycleTurns, (wandererEntity));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function claimCycleTurns(RootCallWrapper memory self, bytes32 wandererEntity) internal {
    bytes memory systemCall = abi.encodeCall(_claimCycleTurns_bytes32.claimCycleTurns, (wandererEntity));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(ClaimCycleTurnsSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ClaimCycleTurnsSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ClaimCycleTurnsSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ClaimCycleTurnsSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ClaimCycleTurnsSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ClaimCycleTurnsSystemType) {
    return ClaimCycleTurnsSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ClaimCycleTurnsSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _claimCycleTurns_bytes32 {
  function claimCycleTurns(bytes32 wandererEntity) external;
}

using ClaimCycleTurnsSystemLib for ClaimCycleTurnsSystemType global;
using ClaimCycleTurnsSystemLib for CallWrapper global;
using ClaimCycleTurnsSystemLib for RootCallWrapper global;
