// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CycleCombatRewardSystem } from "../../cycle/CycleCombatRewardSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type CycleCombatRewardSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "CycleCombatRewar" }))
CycleCombatRewardSystemType constant cycleCombatRewardSystem = CycleCombatRewardSystemType.wrap(
  0x737900000000000000000000000000004379636c65436f6d6261745265776172
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title CycleCombatRewardSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library CycleCombatRewardSystemLib {
  error CycleCombatRewardSystemLib_CallingFromRootSystem();

  function reward(CycleCombatRewardSystemType self, bytes32 wandererEntity, bytes32 requestId) internal {
    return CallWrapper(self.toResourceId(), address(0)).reward(wandererEntity, requestId);
  }

  function cancelRequest(CycleCombatRewardSystemType self, bytes32 wandererEntity, bytes32 requestId) internal {
    return CallWrapper(self.toResourceId(), address(0)).cancelRequest(wandererEntity, requestId);
  }

  function reward(CallWrapper memory self, bytes32 wandererEntity, bytes32 requestId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CycleCombatRewardSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_reward_bytes32_bytes32.reward, (wandererEntity, requestId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function cancelRequest(CallWrapper memory self, bytes32 wandererEntity, bytes32 requestId) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert CycleCombatRewardSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_cancelRequest_bytes32_bytes32.cancelRequest, (wandererEntity, requestId));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function reward(RootCallWrapper memory self, bytes32 wandererEntity, bytes32 requestId) internal {
    bytes memory systemCall = abi.encodeCall(_reward_bytes32_bytes32.reward, (wandererEntity, requestId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function cancelRequest(RootCallWrapper memory self, bytes32 wandererEntity, bytes32 requestId) internal {
    bytes memory systemCall = abi.encodeCall(_cancelRequest_bytes32_bytes32.cancelRequest, (wandererEntity, requestId));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(CycleCombatRewardSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(CycleCombatRewardSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(
    CycleCombatRewardSystemType self,
    address from
  ) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(CycleCombatRewardSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(CycleCombatRewardSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (CycleCombatRewardSystemType) {
    return CycleCombatRewardSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(CycleCombatRewardSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _reward_bytes32_bytes32 {
  function reward(bytes32 wandererEntity, bytes32 requestId) external;
}

interface _cancelRequest_bytes32_bytes32 {
  function cancelRequest(bytes32 wandererEntity, bytes32 requestId) external;
}

using CycleCombatRewardSystemLib for CycleCombatRewardSystemType global;
using CycleCombatRewardSystemLib for CallWrapper global;
using CycleCombatRewardSystemLib for RootCallWrapper global;
