// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RandomEquipmentSystem } from "../../loot/RandomEquipmentSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type RandomEquipmentSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "", name: "RandomEquipmentS" }))
RandomEquipmentSystemType constant randomEquipmentSystem = RandomEquipmentSystemType.wrap(
  0x7379000000000000000000000000000052616e646f6d45717569706d656e7453
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title RandomEquipmentSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library RandomEquipmentSystemLib {
  error RandomEquipmentSystemLib_CallingFromRootSystem();

  function mintRandomEquipmentEntity(
    RandomEquipmentSystemType self,
    uint32 ilvl,
    uint256 randomness
  ) internal returns (bytes32 lootEntity) {
    return CallWrapper(self.toResourceId(), address(0)).mintRandomEquipmentEntity(ilvl, randomness);
  }

  function mintRandomEquipmentEntity(
    CallWrapper memory self,
    uint32 ilvl,
    uint256 randomness
  ) internal returns (bytes32 lootEntity) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert RandomEquipmentSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _mintRandomEquipmentEntity_uint32_uint256.mintRandomEquipmentEntity,
      (ilvl, randomness)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    return abi.decode(result, (bytes32));
  }

  function mintRandomEquipmentEntity(
    RootCallWrapper memory self,
    uint32 ilvl,
    uint256 randomness
  ) internal returns (bytes32 lootEntity) {
    bytes memory systemCall = abi.encodeCall(
      _mintRandomEquipmentEntity_uint32_uint256.mintRandomEquipmentEntity,
      (ilvl, randomness)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    return abi.decode(result, (bytes32));
  }

  function callFrom(RandomEquipmentSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(RandomEquipmentSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(RandomEquipmentSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(RandomEquipmentSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(RandomEquipmentSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (RandomEquipmentSystemType) {
    return RandomEquipmentSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(RandomEquipmentSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _mintRandomEquipmentEntity_uint32_uint256 {
  function mintRandomEquipmentEntity(uint32 ilvl, uint256 randomness) external;
}

using RandomEquipmentSystemLib for RandomEquipmentSystemType global;
using RandomEquipmentSystemLib for CallWrapper global;
using RandomEquipmentSystemLib for RootCallWrapper global;
