// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { StatmodBase, StatmodBaseData } from "./tables/StatmodBase.sol";
import { StatmodValue } from "./tables/StatmodValue.sol";
import { StatmodIdxList } from "./tables/StatmodIdxList.sol";
import { StatmodIdxMap } from "./tables/StatmodIdxMap.sol";
