// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Name, NameTableId } from "./tables/Name.sol";
import { DefaultWheel, DefaultWheelTableId } from "./tables/DefaultWheel.sol";
import { Wheel, WheelData, WheelTableId } from "./tables/Wheel.sol";
import { Experience, ExperienceTableId } from "./tables/Experience.sol";
import { ActiveGuise, ActiveGuiseTableId } from "./tables/ActiveGuise.sol";
import { GuisePrototype, GuisePrototypeTableId } from "./tables/GuisePrototype.sol";
import { LearnedSkills, LearnedSkillsTableId } from "./tables/LearnedSkills.sol";
import { LifeCurrent, LifeCurrentTableId } from "./tables/LifeCurrent.sol";
import { ManaCurrent, ManaCurrentTableId } from "./tables/ManaCurrent.sol";
import { SkillTemplate, SkillTemplateData, SkillTemplateTableId } from "./tables/SkillTemplate.sol";
import { SkillTemplateCooldown, SkillTemplateCooldownData, SkillTemplateCooldownTableId } from "./tables/SkillTemplateCooldown.sol";
import { SkillTemplateDuration, SkillTemplateDurationData, SkillTemplateDurationTableId } from "./tables/SkillTemplateDuration.sol";
import { SkillDescription, SkillDescriptionTableId } from "./tables/SkillDescription.sol";
import { SkillNameToEntity, SkillNameToEntityTableId } from "./tables/SkillNameToEntity.sol";
import { SkillCooldown, SkillCooldownData, SkillCooldownTableId } from "./tables/SkillCooldown.sol";
import { ActiveCycle, ActiveCycleTableId } from "./tables/ActiveCycle.sol";
import { CycleToWanderer, CycleToWandererTableId } from "./tables/CycleToWanderer.sol";
import { CurrentCycle, CurrentCycleTableId } from "./tables/CurrentCycle.sol";
import { PreviousCycle, PreviousCycleTableId } from "./tables/PreviousCycle.sol";
import { CycleTurns, CycleTurnsTableId } from "./tables/CycleTurns.sol";
import { CycleTurnsLastClaimed, CycleTurnsLastClaimedTableId } from "./tables/CycleTurnsLastClaimed.sol";
import { ActiveWheel, ActiveWheelTableId } from "./tables/ActiveWheel.sol";
import { Wanderer, WandererTableId } from "./tables/Wanderer.sol";
import { ActiveCombat, ActiveCombatTableId } from "./tables/ActiveCombat.sol";
import { RNGPrecommit, RNGPrecommitTableId } from "./tables/RNGPrecommit.sol";
import { RNGRequestOwner, RNGRequestOwnerTableId } from "./tables/RNGRequestOwner.sol";
import { SlotAllowedTypes, SlotAllowedTypesTableId } from "./tables/SlotAllowedTypes.sol";
import { SlotEquipment, SlotEquipmentTableId } from "./tables/SlotEquipment.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
import { GenericDuration, GenericDurationData } from "./tables/GenericDuration.sol";
import { DurationIdxList, DurationIdxListTableId } from "./tables/DurationIdxList.sol";
import { DurationIdxMap, DurationIdxMapTableId } from "./tables/DurationIdxMap.sol";
import { StatmodBase, StatmodBaseData, StatmodBaseTableId } from "./tables/StatmodBase.sol";
import { StatmodValue, StatmodValueTableId } from "./tables/StatmodValue.sol";
import { StatmodIdxList, StatmodIdxListTableId } from "./tables/StatmodIdxList.sol";
import { StatmodIdxMap, StatmodIdxMapTableId } from "./tables/StatmodIdxMap.sol";
import { EffectDuration, EffectDurationData, EffectDurationTableId } from "./tables/EffectDuration.sol";
import { EffectTemplate, EffectTemplateData, EffectTemplateTableId } from "./tables/EffectTemplate.sol";
import { EffectApplied, EffectAppliedData, EffectAppliedTableId } from "./tables/EffectApplied.sol";
