// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Name, NameTableId } from "./tables/Name.sol";
import { DefaultWheel, DefaultWheelTableId } from "./tables/DefaultWheel.sol";
import { Wheel, WheelData, WheelTableId } from "./tables/Wheel.sol";
import { Experience, ExperienceTableId } from "./tables/Experience.sol";
import { ActiveGuise, ActiveGuiseTableId } from "./tables/ActiveGuise.sol";
import { GuisePrototype, GuisePrototypeTableId } from "./tables/GuisePrototype.sol";
import { LearnedSkills, LearnedSkillsTableId } from "./tables/LearnedSkills.sol";
import { LifeCurrent, LifeCurrentTableId } from "./tables/LifeCurrent.sol";
import { ManaCurrent, ManaCurrentTableId } from "./tables/ManaCurrent.sol";
import { SkillTemplate, SkillTemplateData, SkillTemplateTableId } from "./tables/SkillTemplate.sol";
import { EffectTemplate, EffectTemplateData, EffectTemplateTableId } from "./tables/EffectTemplate.sol";
import { StatmodBase, StatmodBaseData, StatmodBaseTableId } from "./tables/StatmodBase.sol";
import { StatmodValue, StatmodValueTableId } from "./tables/StatmodValue.sol";
import { StatmodIdxList, StatmodIdxListTableId } from "./tables/StatmodIdxList.sol";
import { StatmodIdxMap, StatmodIdxMapTableId } from "./tables/StatmodIdxMap.sol";
import { ActiveCombat, ActiveCombatTableId } from "./tables/ActiveCombat.sol";
import { ActiveCycle, ActiveCycleTableId } from "./tables/ActiveCycle.sol";
import { CycleTurns, CycleTurnsTableId } from "./tables/CycleTurns.sol";
import { CycleTurnsLastClaimed, CycleTurnsLastClaimedTableId } from "./tables/CycleTurnsLastClaimed.sol";
import { RNGPrecommit, RNGPrecommitTableId } from "./tables/RNGPrecommit.sol";
import { RNGRequestOwner, RNGRequestOwnerTableId } from "./tables/RNGRequestOwner.sol";
