// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Experience, ExperienceTableId } from "./tables/Experience.sol";
import { ActiveGuise, ActiveGuiseTableId } from "./tables/ActiveGuise.sol";
import { GuisePrototype, GuisePrototypeTableId } from "./tables/GuisePrototype.sol";
import { ActiveCycle, ActiveCycleTableId } from "./tables/ActiveCycle.sol";
import { CurrentCycle, CurrentCycleTableId } from "./tables/CurrentCycle.sol";
import { PreviousCycle, PreviousCycleTableId } from "./tables/PreviousCycle.sol";
import { ActiveWheel, ActiveWheelTableId } from "./tables/ActiveWheel.sol";
import { Wheel, WheelData, WheelTableId } from "./tables/Wheel.sol";
import { Wanderer, WandererTableId } from "./tables/Wanderer.sol";
