// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Experience, ExperienceTableId } from "./tables/Experience.sol";
import { ActiveGuise, ActiveGuiseTableId } from "./tables/ActiveGuise.sol";
import { GuisePrototype, GuisePrototypeTableId } from "./tables/GuisePrototype.sol";
import { EqptBase, EqptBaseTableId } from "./tables/EqptBase.sol";
import { FromEqptBase, FromEqptBaseTableId } from "./tables/FromEqptBase.sol";
import { SlotAllowedBases, SlotAllowedBasesTableId } from "./tables/SlotAllowedBases.sol";
import { SlotEquipment, SlotEquipmentTableId } from "./tables/SlotEquipment.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { OwnedBy, OwnedByTableId } from "./tables/OwnedBy.sol";
