// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RNGPrecommit } from "./tables/RNGPrecommit.sol";
import { RNGRequestOwner } from "./tables/RNGRequestOwner.sol";
