// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { SlotAllowedType } from "./tables/SlotAllowedType.sol";
import { SlotEquipment } from "./tables/SlotEquipment.sol";
import { EquipmentTypeComponent } from "./tables/EquipmentTypeComponent.sol";
