// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Wheel, WheelData } from "./tables/Wheel.sol";
import { ActiveWheel } from "./tables/ActiveWheel.sol";
import { WheelsCompleted } from "./tables/WheelsCompleted.sol";
import { IdentityCurrent } from "./tables/IdentityCurrent.sol";
import { IdentityEarnedTotal } from "./tables/IdentityEarnedTotal.sol";
