// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InitCycleSystem } from "../../InitCycleSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type InitCycleSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "cycle", name: "InitCycleSystem" }))
InitCycleSystemType constant initCycleSystem = InitCycleSystemType.wrap(
  0x73796379636c65000000000000000000496e69744379636c6553797374656d00
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title InitCycleSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library InitCycleSystemLib {
  error InitCycleSystemLib_CallingFromRootSystem();
  error InitCycleSystem_DuplicateActiveCycle();
  error InitCycleSystem_InvalidGuiseEntity();

  function initCycle(
    InitCycleSystemType self,
    bytes32 wandererEntity,
    bytes32 guiseEntity,
    bytes32 wheelEntity
  ) internal returns (bytes32 cycleEntity) {
    return CallWrapper(self.toResourceId(), address(0)).initCycle(wandererEntity, guiseEntity, wheelEntity);
  }

  function initCycle(
    CallWrapper memory self,
    bytes32 wandererEntity,
    bytes32 guiseEntity,
    bytes32 wheelEntity
  ) internal returns (bytes32 cycleEntity) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert InitCycleSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _initCycle_bytes32_bytes32_bytes32.initCycle,
      (wandererEntity, guiseEntity, wheelEntity)
    );

    bytes memory result = self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
    return abi.decode(result, (bytes32));
  }

  function initCycle(
    RootCallWrapper memory self,
    bytes32 wandererEntity,
    bytes32 guiseEntity,
    bytes32 wheelEntity
  ) internal returns (bytes32 cycleEntity) {
    bytes memory systemCall = abi.encodeCall(
      _initCycle_bytes32_bytes32_bytes32.initCycle,
      (wandererEntity, guiseEntity, wheelEntity)
    );

    bytes memory result = SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
    return abi.decode(result, (bytes32));
  }

  function callFrom(InitCycleSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(InitCycleSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(InitCycleSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(InitCycleSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(InitCycleSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (InitCycleSystemType) {
    return InitCycleSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(InitCycleSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _initCycle_bytes32_bytes32_bytes32 {
  function initCycle(bytes32 wandererEntity, bytes32 guiseEntity, bytes32 wheelEntity) external;
}

using InitCycleSystemLib for InitCycleSystemType global;
using InitCycleSystemLib for CallWrapper global;
using InitCycleSystemLib for RootCallWrapper global;
