// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";

// Import idx internals
import { Uint8Map, Uint8MapLib } from "@dk1a/mud-table-idxs/src/Uint8Map.sol";
import { hashIndexes, hashValues } from "@dk1a/mud-table-idxs/src/utils.sol";

import { IIdxErrors } from "@dk1a/mud-table-idxs/src/IIdxErrors.sol";

import { registerBasicIdx } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/registerBasicIdx.sol";
import { BasicIdx } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/codegen/tables/BasicIdx.sol";
import { BasicIdxUsedKeys } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/codegen/tables/BasicIdxUsedKeys.sol";
import { BasicIdx_KeyTuple } from "@dk1a/mud-table-idxs/src/namespaces/basicIdx/BasicIdx_KeyTuple.sol";

library Idx_GenericDuration_TargetEntityTimeId {
  uint256 constant _keyNumber = 1;
  uint256 constant _fieldNumber = 1;

  Uint8Map constant _keyIndexes = Uint8Map.wrap(0x0100000000000000000000000000000000000000000000000000000000000000);
  Uint8Map constant _fieldIndexes = Uint8Map.wrap(0x0100000000000000000000000000000000000000000000000000000000000000);

  bytes32 constant _indexesHash = 0xe67bd8207455ea87f57a80a93cab0dcc2071e17e8131072897c656e2333c7496;

  function valuesHash(bytes32 targetEntity, bytes32 timeId) internal pure returns (bytes32) {
    bytes32[] memory _partialKeyTuple = new bytes32[](_keyNumber);

    _partialKeyTuple[0] = targetEntity;

    bytes[] memory _partialValues = new bytes[](_fieldNumber);

    _partialValues[0] = abi.encodePacked((timeId));

    return hashValues(_partialKeyTuple, _partialValues);
  }

  // Should be called once in e.g. PostDeploy
  function register(ResourceId _tableId) internal {
    registerBasicIdx(_tableId, _keyIndexes, _fieldIndexes);
  }

  function length(ResourceId _tableId, bytes32 targetEntity, bytes32 timeId) internal view returns (uint256) {
    bytes32 _valuesHash = valuesHash(targetEntity, timeId);

    return BasicIdx_KeyTuple.length(_tableId, _indexesHash, _valuesHash);
  }

  function hasKeyTuple(
    ResourceId _tableId,
    bytes32[] memory _keyTuple
  ) internal view returns (bool _has, uint40 _index) {
    bytes32 _keyTupleHash = keccak256(abi.encode(_keyTuple));

    return BasicIdxUsedKeys.get(_tableId, _indexesHash, _keyTupleHash);
  }

  function has(
    ResourceId _tableId,
    bytes32 targetEntity,
    bytes32 applicationEntity
  ) internal view returns (bool _has, uint40 _index) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = targetEntity;
    _keyTuple[1] = applicationEntity;

    return hasKeyTuple(_tableId, _keyTuple);
  }

  function getKeyTuple(
    ResourceId _tableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index
  ) internal view returns (bytes32[] memory _keyTuple) {
    bytes32 _valuesHash = valuesHash(targetEntity, timeId);

    _keyTuple = BasicIdx_KeyTuple.getItem(_tableId, _indexesHash, _valuesHash, _index, 2);
  }

  function get(
    ResourceId _tableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index
  ) internal view returns (bytes32 applicationEntity) {
    bytes32[] memory _keyTuple = getKeyTuple(_tableId, targetEntity, timeId, _index);

    targetEntity = _keyTuple[0];

    applicationEntity = _keyTuple[1];
  }

  /**
   * @notice Decode keys from a bytes32 array using the source table's field layout.
   */
  function decodeKeyTuple(
    bytes32[] memory _keyTuple
  ) internal pure returns (bytes32 targetEntity, bytes32 applicationEntity) {
    targetEntity = _keyTuple[0];

    applicationEntity = _keyTuple[1];
  }
}
