// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { AffixPrototype, AffixPrototypeData } from "./tables/AffixPrototype.sol";
import { Affix, AffixData } from "./tables/Affix.sol";
import { AffixPrototypeAvailable } from "./tables/AffixPrototypeAvailable.sol";
import { AffixNaming } from "./tables/AffixNaming.sol";
