// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICommonSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICommonSystem {
  function common__setName(bytes32 entity, string memory name) external;

  function common__setOwnedBy(bytes32 entity, bytes32 ownerEntity) external;
}
