// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICycleNoncombatSkillSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICycleNoncombatSkillSystem {
  function cycle__castNoncombatSkill(bytes32 cycleEntity, bytes32 skillEntity) external;
}
