// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICycleCombatRewardSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICycleCombatRewardSystem {
  function claimCycleCombatReward(bytes32 wandererEntity, bytes32 requestId) external;

  function cancelCycleCombatReward(bytes32 wandererEntity, bytes32 requestId) external;
}
