// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ICycleCombatRewardSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICycleCombatRewardSystem {
  error CycleCombatRewardSystem__UnknownMapPrototype();

  function reward(bytes memory args) external returns (bytes memory);

  function cancelRequest(bytes32 wandererEntity, bytes32 requestId) external;
}
