// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EquipmentType } from "../../namespaces/equipment/EquipmentType.sol";

/**
 * @title IEquipmentSlotSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEquipmentSlotSystem {
  error EquipmentSlotSystem_InvalidEquipmentType(EquipmentType equipmentType);

  function equipment__createEquipmentSlot(
    bytes32 ownerEntity,
    string memory name,
    EquipmentType equipmentType
  ) external returns (bytes32 slotEntity);

  function equipment__createEquipmentSlot(
    bytes32 ownerEntity,
    string memory name,
    EquipmentType[] memory equipmentTypes
  ) external returns (bytes32 slotEntity);
}
