// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EquipmentType } from "../../namespaces/equipment/EquipmentType.sol";

/**
 * @title IEquipmentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEquipmentSystem {
  error EquipmentSystem_InvalidEquipmentType(bytes32 equipmentEntity);
  error EquipmentSystem_SlotNotAllowedForType(bytes32 slotEntity, EquipmentType equipmentType, bytes32 equipmentEntity);
  error EquipmentSystem_EquipmentEntityAlreadyEquipped(bytes32 equipmentEntity);

  function equipment__unequip(bytes32 targetEntity, bytes32 slotEntity) external;

  function equipment__equip(bytes32 targetEntity, bytes32 slotEntity, bytes32 equipmentEntity) external;

  function equipment__spawnEquipmentSlots(bytes32 ownerEntity) external;
}
