// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILearnCycleSkillSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILearnCycleSkillSystem {
  error LearnCycleSkillSystem_SkillNotInGuiseSkills();
  error LearnCycleSkillSystem_LevelIsTooLow();

  function learnFromCycle(bytes32 wandererEntity, bytes32 skillEntity) external;
}
