// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPermSkillSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPermSkillSystem {
  error PermSkillSystem_NoPreviousCycle();
  error PermSkillSystem_SkillNotLearnedInLastCompletedCycle(bytes32 prevCycleEntity);
  error PermSkillSystem_NotEnoughIdentity();

  function wanderer__permSkill(bytes32 wandererEntity, bytes32 skillEntity) external;
}
