// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRandomEquipmentSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRandomEquipmentSystem {
  function loot__mintRandomEquipmentEntity(uint32 ilvl, uint256 randomness) external returns (bytes32 lootEntity);
}
