// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IRNGSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IRNGSystem {
  function rng__requestRandomness(bytes32 requestOwnerEntity) external returns (bytes32 requestId);

  function rng__removeRequest(bytes32 requestOwnerEntity, bytes32 requestId) external;
}
