// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITimeSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITimeSystem {
  function time__passTurns(bytes32 targetEntity, uint256 timeValue) external;

  function time__passRounds(bytes32 targetEntity, uint256 timeValue) external;
}
