// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { ICombatSystem } from "./ICombatSystem.sol";
import { ICycleInitSystem } from "./ICycleInitSystem.sol";
import { IPassCycleTurnSystem } from "./IPassCycleTurnSystem.sol";
import { IStartCycleSystem } from "./IStartCycleSystem.sol";
import { IWandererSpawnSystem } from "./IWandererSpawnSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  ICombatSystem,
  ICycleInitSystem,
  IPassCycleTurnSystem,
  IStartCycleSystem,
  IWandererSpawnSystem
{}
