// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library DurationIdxList {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "duration", name: "DurationIdxList", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74626475726174696f6e0000000000004475726174696f6e4964784c69737400);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x006003005f5f5f00000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bytes32[])
  Schema constant _valueSchema = Schema.wrap(0x00000001c1000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](3);
    keyNames[0] = "sourceTableId";
    keyNames[1] = "targetEntity";
    keyNames[2] = "timeId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "applicationEntities";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get applicationEntities.
   */
  function getApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId
  ) internal view returns (bytes32[] memory applicationEntities) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get applicationEntities.
   */
  function _getApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId
  ) internal view returns (bytes32[] memory applicationEntities) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get applicationEntities.
   */
  function get(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId
  ) internal view returns (bytes32[] memory applicationEntities) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Get applicationEntities.
   */
  function _get(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId
  ) internal view returns (bytes32[] memory applicationEntities) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_bytes32());
  }

  /**
   * @notice Set applicationEntities.
   */
  function setApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    bytes32[] memory applicationEntities
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((applicationEntities)));
  }

  /**
   * @notice Set applicationEntities.
   */
  function _setApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    bytes32[] memory applicationEntities
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((applicationEntities)));
  }

  /**
   * @notice Set applicationEntities.
   */
  function set(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    bytes32[] memory applicationEntities
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((applicationEntities)));
  }

  /**
   * @notice Set applicationEntities.
   */
  function _set(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    bytes32[] memory applicationEntities
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((applicationEntities)));
  }

  /**
   * @notice Get the length of applicationEntities.
   */
  function lengthApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of applicationEntities.
   */
  function _lengthApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId
  ) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of applicationEntities.
   */
  function length(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of applicationEntities.
   */
  function _length(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of applicationEntities.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of applicationEntities.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of applicationEntities.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Get an item of applicationEntities.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItem(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index
  ) internal view returns (bytes32) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (bytes32(_blob));
    }
  }

  /**
   * @notice Push an element to applicationEntities.
   */
  function pushApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to applicationEntities.
   */
  function _pushApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to applicationEntities.
   */
  function push(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to applicationEntities.
   */
  function _push(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId, bytes32 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from applicationEntities.
   */
  function popApplicationEntities(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from applicationEntities.
   */
  function _popApplicationEntities(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from applicationEntities.
   */
  function pop(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from applicationEntities.
   */
  function _pop(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of applicationEntities at `_index`.
   */
  function updateApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of applicationEntities at `_index`.
   */
  function _updateApplicationEntities(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of applicationEntities at `_index`.
   */
  function update(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of applicationEntities at `_index`.
   */
  function _update(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId,
    uint256 _index,
    bytes32 _element
  ) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(ResourceId sourceTableId, bytes32 targetEntity, bytes32 timeId) internal {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(bytes32[] memory applicationEntities) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(applicationEntities.length * 32);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(bytes32[] memory applicationEntities) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((applicationEntities)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bytes32[] memory applicationEntities
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(applicationEntities);
    bytes memory _dynamicData = encodeDynamic(applicationEntities);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(
    ResourceId sourceTableId,
    bytes32 targetEntity,
    bytes32 timeId
  ) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](3);
    _keyTuple[0] = ResourceId.unwrap(sourceTableId);
    _keyTuple[1] = targetEntity;
    _keyTuple[2] = timeId;

    return _keyTuple;
  }
}
