// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { UniqueIdx_SkillName_Name } from "./idxs/UniqueIdx_SkillName_Name.sol";

function batchRegisterIdxs() {
  UniqueIdx_SkillName_Name.register();
}
